Add tests
lastperson/ethse pull request #1
Opened 2017-04-16 21:04 UTC by viatrix

2017-04-17 05:17 UTC, lastperson requested changes
Is there any other cases? Will multiple different borrowers work alright? Maybe need to check other getters of the contract?

2017-04-17 05:17 UTC, lastperson commented on test/debts.js
> +  it('should fail on overflow when repaying', () => {
What about the overflow when borrowing?

2017-04-17 05:17 UTC, lastperson commented on test/debts.js
> +  it('should emit Repayed event on repay', () => {
Is there any other events in the contract?

2017-04-17 06:56 UTC, viatrix commented on test/debts.js
> +  it('should emit Repayed event on repay', () => {
'Borrowed' event was already checked in 'should emit Borrowed event on borrow' test

2017-04-17 06:57 UTC, viatrix commented on test/debts.js
> +  it('should fail on overflow when repaying', () => {
This case was already checked in 'should fail on overflow when borrowing' test

2017-04-17 06:58 UTC, lastperson commented on test/debts.js
> +  it('should fail on overflow when repaying', () => {
right, my bad, was only looking at the changes.

2017-04-17 06:59 UTC, lastperson commented on test/debts.js
> +  it('should emit Repayed event on repay', () => {
Same, forgot about current ver.

2017-04-20 03:41 UTC, lastperson reviewed
I like it!

2017-04-20 03:41 UTC, lastperson approved these changes

2017-10-30 10:14 UTC, closed without merging