complete tests list
lastperson/ethse pull request #8
Opened 2017-10-31 20:29 UTC by yurunhub

2017-11-01 17:30 UTC, lastperson approved these changes
What should happen on zero borrow or repay?

2017-11-01 17:30 UTC, lastperson commented on test/debts.js
> +    .then(asserts.equal(1000));
You already have value const, maybe use it here?

2017-11-03 15:52 UTC, yurunhub commented
>What should happen on zero borrow or repay?

Per my understanding there should not be an Event emitted, however Depts.sol contract would not pass this check so I only added the check in my Lender.sol contract and tests

2017-11-05 20:56 UTC, lastperson requested changes
All the functions call results should indicate to caller if they went alright or failed. In your case functions with onlyOwner/onlyNotOwner silently fail in modifier, and caller cannot verify if it failed or not.

2017-11-05 20:56 UTC, lastperson commented on test/lender.js
> +  it('should fail on overflow when requesting money', () => {
is there an overflow or something else?

2017-11-05 20:56 UTC, lastperson commented on test/lender.js
> +
test for borrowing 50000000 and then another 50000001.

2017-11-18 11:32 UTC, lastperson approved these changes

2018-03-20 10:44 UTC, closed without merging