tests from Gromova
lastperson/ethse pull request #9
Opened 2017-11-01 16:17 UTC by Purka

I'm not sure I'm doing it right it's a bit harder than games

2017-11-01 17:55 UTC, lastperson approved these changes
What should happen with partial repayment?
What should happen with 0 borrow or 0 repayment?
Any othe cases to cover?

2017-11-01 17:55 UTC, lastperson commented on test/debts.js
> +    const underValue = '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff';
In order for underflow to happen, you just need a number bigger than value itself, say 101. But this also works.

2017-11-01 17:55 UTC, lastperson commented on test/debts.js
> +  it('added: should not to be overpaid when repaing', () => {
pretty much the same covered above.

2017-11-03 09:27 UTC, Purka commented
I've added some more tests. I couldn't think of more ._.

2017-11-04 12:03 UTC, Purka commented
I've done and ready for feedback

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +        } else if (requested[msg.sender] + _amount < requested[msg.sender]) {
If there is a return statement in 'if' then maybe you can use just 'if' instead of 'else if' on the next line? Probably will become easier to read.

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +            Error("Zero is not valid");
indentation

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +            } else if (requested[msg.sender] - _amount > requested[msg.sender]) {
`if (requested < _amount)` maybe it is simpler this way?

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +            requested[_requester] -= amount;
requested = 0 ?

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +            requested[_requester] -= amount;
having the successful outcome somewhere inbetween fail outcomes confuses reader.

2017-11-06 13:44 UTC, lastperson commented on contracts/Borrow.sol
> +            require(borrows[msg.sender] >= _amount);
Is there a trst for this check?

2017-11-07 10:35 UTC, Purka commented on contracts/Borrow.sol
> +            require(borrows[msg.sender] >= _amount);
Yes, it('should not be overpaid when repaying')
But actually, this line is redundant. I'll fix it

2017-11-18 11:52 UTC, lastperson requested changes
1. Is it possible to play another game after the first one?
2. What if players don't withdraw and another game starts?

2017-11-18 11:52 UTC, lastperson commented on contracts/OXO.sol
> +	function isWinner(byte s) public returns (bool success) {
Looks like constant.

2017-11-20 13:18 UTC, lastperson requested changes
There is also places of code duplication that can be refactored.

2017-11-20 13:18 UTC, lastperson commented on test/oxotest.js
> +	it('shoud allow to play again after returnDeposit', () => {
not finished?

2017-11-20 13:18 UTC, lastperson commented on contracts/OXO.sol
> +			if (lastMove == '0') {
If there is not tests, then there is most probably a bug.

2018-03-20 10:44 UTC, lastperson approved these changes

2018-03-20 10:44 UTC, closed without merging